//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim()
        {
            this.AccessGroupClaims = new HashSet<AccessGroupClaims>();
        }
    
        public int ClaimId { get; set; }
        [Required(ErrorMessage = "Claim Name is required")]
        [MaxLength(256, ErrorMessage = "Maximum 256 characters exceeded")]
        public string ClaimName { get; set; }
        [Required(ErrorMessage = "Claim Value is required")]
        public string ClaimValue { get; set; }
        public string SubOperation { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessGroupClaims> AccessGroupClaims { get; set; }
    }
}
