//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConductedLectures
    {
        public int CLId { get; set; }
        public string LecturerId { get; set; }
        public System.DateTime LectureDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int LectureTypeId { get; set; }
        public int LectureHallId { get; set; }
        public int Location { get; set; }
        public int StudentBatchId { get; set; }
        public int StudentCount { get; set; }
        public string StudentAttendanceSheet { get; set; }
        public int ApprovalStageId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ApprovalStages ApprovalStages { get; set; }
        public virtual Campus Campus { get; set; }
        public virtual LectureHall LectureHall { get; set; }
        public virtual LectureType LectureType { get; set; }
        public virtual StudentBatch StudentBatch { get; set; }
    }
}
