//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ConfigurationalSettings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigurationalSettings()
        {
            this.SubConfigurationalSettings = new HashSet<SubConfigurationalSettings>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Configuration Key is required")]
        [MaxLength(250, ErrorMessage = "Maximum 250 characters exceeded")]
        public string ConfigurationKey { get; set; }
        public string ConfigurationValue { get; set; }
        public bool IsFacultyWise { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubConfigurationalSettings> SubConfigurationalSettings { get; set; }
    }
}
