/* Developed By:- Dulanjalee Wickremasinghe
    Developed On:- 2022/08/19*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ConfigurationalSettings
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Configuration Key is required")]
        [MaxLength(250, ErrorMessage = "Maximum 250 characters exceeded")]
        public string ConfigurationKey { get; set; }
        [Required(ErrorMessage = "Configuration Value is required")]
        [MaxLength(150, ErrorMessage = "Maximum 150 characters exceeded")]
        public string ConfigurationValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
