//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LectureHall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LectureHall()
        {
            this.ConductedLectures = new HashSet<ConductedLectures>();
            this.ConductedLecturesLog = new HashSet<ConductedLecturesLog>();
            this.LectureTimetable = new HashSet<LectureTimetable>();
            this.LectureTimetableLog = new HashSet<LectureTimetableLog>();
        }
    
        public int HallId { get; set; }
        [Required(ErrorMessage = "Campus is required")]
        public int CampusId { get; set; }
        [Required(ErrorMessage = "Building is required")]
        [MaxLength(150, ErrorMessage = "Maximum 150 characters exceeded")]
        public string Building { get; set; }
        [Required(ErrorMessage = "Floor is required")]
        [MaxLength(150, ErrorMessage = "Maximum 150 characters exceeded")]
        public string Floor { get; set; }
        [Required(ErrorMessage = "Hall Name is required")]
        [MaxLength(150, ErrorMessage = "Maximum 150 characters exceeded")]
        public string HallName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Campus Campus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConductedLectures> ConductedLectures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConductedLecturesLog> ConductedLecturesLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LectureTimetable> LectureTimetable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LectureTimetableLog> LectureTimetableLog { get; set; }
    }
}
