//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureTimetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LectureTimetable()
        {
            this.ConductedLectures = new HashSet<ConductedLectures>();
            this.ConductedLecturesLog = new HashSet<ConductedLecturesLog>();
            this.LectureTimetableLog = new HashSet<LectureTimetableLog>();
        }
    
        public int TimetableId { get; set; }
        public int SemesterId { get; set; }
        public int SemesterSubjectId { get; set; }
        public Nullable<System.DateTime> LectureDate { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int LectureTypeId { get; set; }
        public string LecturerId { get; set; }
        public string StudentBatches { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConductedLectures> ConductedLectures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConductedLecturesLog> ConductedLecturesLog { get; set; }
        public virtual LectureHall LectureHall { get; set; }
        public virtual LectureType LectureType { get; set; }
        public virtual SemesterRegistration SemesterRegistration { get; set; }
        public virtual SemesterSubject SemesterSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LectureTimetableLog> LectureTimetableLog { get; set; }
    }
}
