//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PaymentRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentRate()
        {
            this.PaymentRateLog = new HashSet<PaymentRateLog>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DegreeId { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        [Required(ErrorMessage = "Faculty is required")]
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        [Required(ErrorMessage = "Designation is required")]
        public int DesignationId { get; set; }
        [Required(ErrorMessage = "Lecture Type is required")]
        public Nullable<int> LectureTypeId { get; set; }
        [Required(ErrorMessage = "Rate Per Hour is required")]
        [Range(0, int.MaxValue, ErrorMessage = "Only positive values are allowed")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public double RatePerHour { get; set; }
        public double OldRatePerHour { get; set; }
        public Nullable<bool> SentForApproval { get; set; }
        public string SentToApprovalBy { get; set; }
        public Nullable<System.DateTime> SentToApprovalDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApprovalOrRejectionRemark { get; set; }
        public string ApprovedOrRejectedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOrRejectedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual LectureType LectureType { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRateLog> PaymentRateLog { get; set; }
    }
}
