//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SemesterSubjectLIC
    {
        public int SSLICId { get; set; }
        [Required(ErrorMessage = "Semester Subject is required")]
        public int SemesterSubjectId { get; set; }
        [Required(ErrorMessage = "LIC Name is required")]
        public string LICId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual SemesterSubject SemesterSubject { get; set; }
    }
}
