//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SubConfigurationalSettings
    {
        public int SubCSId { get; set; }
        public int CSId { get; set; }
        [Required(ErrorMessage = "Faculty is required")]
        public Nullable<int> FacultyId { get; set; }
        public string ConfigurationValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ConfigurationalSettings ConfigurationalSettings { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
