//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.PaymentRate = new HashSet<PaymentRate>();
            this.PaymentRateLog = new HashSet<PaymentRateLog>();
            this.SemesterSubject = new HashSet<SemesterSubject>();
        }
    
        public int SubjectId { get; set; }
        [Required(ErrorMessage = "Subject Code is required")]
        [MaxLength(100, ErrorMessage = "Maximum 100 characters exceeded")]
        public string SubjectCode { get; set; }
        [Required(ErrorMessage = "Subject Name is required")]
        [MaxLength(200, ErrorMessage = "Maximum 200 characters exceeded")]
        public string SubjectName { get; set; }
        public bool IsCommon { get; set; }
        //[Required(ErrorMessage = "Degree is required")]
        public Nullable<int> DegreeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Degree Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRate> PaymentRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRateLog> PaymentRateLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemesterSubject> SemesterSubject { get; set; }
    }
}
